packaging_format = 2

id = "memos"
name = "Memos"
description.en = "Lightweight note-taking solution"
description.fr = "Solution légère de prise de notes"

version = "0.29.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://demo.usememos.com"
website = "https://usememos.com/"
admindoc = "https://usememos.com/docs"
code = "https://github.com/usememos/memos"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/usememos/memos/releases/download/v0.29.0/memos_0.29.0_linux_amd64.tar.gz"
        amd64.sha256 = "e6e036b5328b2f2240164cecd86cf8b039c0e831a917a9149abb0810d4848e1b"
        arm64.url = "https://github.com/usememos/memos/releases/download/v0.29.0/memos_0.29.0_linux_arm64.tar.gz"
        arm64.sha256 = "ed8379f95250ecff330332d403182120e7498032006e1e73d91cf0f1831087be"

        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*_linux_amd64.tar.gz"
        autoupdate.asset.arm64 = ".*_linux_arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/memos.api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
