#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing nodejs..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Self-hosted memo hub" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL MEMOS
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir/web"
 	ynh_hide_warningsynh_exec_as_app yarn
    ynh_hide_warningsynh_exec_as_app yarn build
popd

cp $install_dir/web/dist $install_dir/server/dist

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

ynh_go_install

pushd $install_dir/
    go build -o memos ./main.go
	#ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=0 go build -o $install_dir/memos
popd

ynh_remove_go
#ynh_safe_rm --file="$install_dir/.cache/"
#ynh_safe_rm --file="$install_dir/go/"
#ynh_safe_rm --file="$install_dir/.go-version"

chmod +x "$install_dir/memos"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
